### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by swjung0826** [Project-jung/Greeting_REPO#1]
CRUD 주제 목록
  1. CAFE 디저트 자판기
  2. 출퇴근 관리 시스템
  3. 스터디 카페 예약 시스템
  4. 가계부 프로그램
  5. 교내 라운지 예약 시스템
  6. 음료 자판기
  등등...

**Comment by daahunii** [comment]
어떤게 좋을까나?

**Comment by daahunii** [comment]
나는 음료 자판기가 간단하게 빨리 만들 수 있을 것 같아

**Comment by swjung0826** [comment]
좋아 좋아 함수 구현하기에도 좋은 주제 같다!

**Comment by daahunii** [comment]
Okay!
